apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-chamber
spec:
  selector:
    matchLabels:
      app: echo-chamber
  template:
    metadata:
      labels:
        app: echo-chamber
    spec:
      containers:
        - name: echo-chamber
          image: mfigurski80/echo-chamber:ce4df20
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-chamber
spec:
  selector:
    app: echo-chamber
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
